"""add email to doctor model

Revision ID: 52be7bb26ee4
Revises: f140ccc9d660
Create Date: 2025-12-05 22:18:19.593414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52be7bb26ee4'
down_revision: Union[str, None] = 'f140ccc9d660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('emails', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'emails')
    # ### end Alembic commands ###
