"""init

Revision ID: f140ccc9d660
Revises: 8f5bf5ad4be3
Create Date: 2025-12-04 14:20:09.326024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f140ccc9d660'
down_revision: Union[str, None] = '8f5bf5ad4be3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('room', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'room')
    # ### end Alembic commands ###
