"""init

Revision ID: f140ccc9d660
Revises: 8f5bf5ad4be3
Create Date: 2025-12-04 14:20:09.326024

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f140ccc9d660"
down_revision: Union[str, None] = "8f5bf5ad4be3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_name='doctors' AND column_name='room'
        ) THEN
            ALTER TABLE doctors ADD COLUMN room VARCHAR(10);
        END IF;
    END
    $$;
    """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("doctors", "room")
    # ### end Alembic commands ###
